---
#<% require 'kitchen-sync' %>
driver:
  name: vagrant
#  network:
#    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -v 12.5.1
  data_bags_path: data_bags
  attributes:
    automation: true

platforms:
  - name: ubuntu-14.04
#  - name: centos-6.7

suites:
  - name: primary
    driver:
      network:
        - ["private_network", {ip: "192.168.33.33"}]
      vm_hostname: ldap01.dapl.com
    run_list:
      - recipe[dapl::primary]
    attributes:
  - name: secondary
    driver:
      network:
        - ["private_network", {ip: "192.168.33.34"}]
      vm_hostname: ldap02.dapl.com
    run_list:
      - recipe[dapl::secondary]
    attributes:
