name             'dapl'
maintainer       'Shawn Catanzarite'
maintainer_email 'me@shawncatz.com'
license          'all_rights'
description      'Installs/Configures dapl'
long_description 'Installs/Configures dapl'
version          '0.1.0'

supports 'ubuntu'

depends 'apt'
depends 'ubuntu'
depends 'apparmor'
depends 'hostsfile'
depends 'ssl'
